{% set name = "logilab-common" %}
{% set version = "1.4.3" %}
{% set sha256 = "ed94546f033d90650a3432a6786b1ba32d3c207f47fe8df58b195746655c88ff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - logilab
    - logilab.common
    - logilab.common.ureports

about:
  home: http://www.logilab.org/project/logilab-common
  license: LGPL 2.1
  summary: 'collection of low-level Python packages and modules used by Logilab projects'

extra:
  recipe-maintainers:
    - jakirkham
