{% set name = "logilab-common" %}
{% set version = "1.7.3" %}
{% set sha256 = "ac08bd39f76b8e4834a2c2d32919472297550f12da59eed332124a74dfb0a40b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - logilab
    - logilab.common
    - logilab.common.ureports

about:
  home: http://www.logilab.org/project/logilab-common
  license: LGPL 2.1
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'collection of low-level Python packages and modules used by Logilab projects'

extra:
  recipe-maintainers:
    - jakirkham
