# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HO11b/+5uRCkIIqTpKiTdUj486fEC56M+xIN8I2Dl1nOxoc/OM6OROAgxkmYDV8YKh8c2DhS9VThMIQ601J4bea0IJ1sT9HtRRDeYMeJFofB/P2TAB7gwc2MI8euTJuOtSlavlfQyXU5wIYbTCuArZtnsCUk73mqyJi9T89Imxs1V7T5nOaDjjKwJH+JpAedxixiah7DOGhE/Wvvcw77wqCR3qZ/OEaAWsYPGLQVAK8FSYY94ls2nSHlEpdNTAqVDXjAM7rQIo9Uan6/NguNDC9vNDTg7XntSxIXKPyENtbQpUTaEca8ufPxugOe2jjtT/wBbZ7TPKA8bDmiJe+eu1T+hMdrK36cNorjXdiNb/gp4c0Ncsm49i232fIZ8JoW/UIk/mUGSQysulPBFImDGnzkBHH44SkP5KRLHtmS2nV7TBX9sq2JUaR7Mu8FzJqDh/uDYVy/lcmVsThbSVK/l3gminmdlWMh+ytIdixJdcgq3ADd08sF3ZKoF26c9OW/cLbcbnm40xpj75bLxhhsZ5mM+HZZnn0r0wYXzk1feTo5+NhlOGgRabisfoKWH+KswjTTyyHDyr0xYHCo36csIsBPHHDOwMFCN/e9TfRfzjB7sJ162r23oCQ80fUNEK4fo2F2w9idqwyabR1x5f8+hCH1fjOtO7oRU1gErDkTJnI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
