travis:
  secure:
    BINSTAR_TOKEN: j1qNDfr9cJqjtgAdGjCQUDcGJHnekPigVNE4omdDru0EIsi9f4z+hpZDmaRsd8Z6IXhsqm9V+yPstH6MmcKSx+wRvhMimIWPGVxEO+SGBBkNyfOg85/V3vPenqTkCOpCzOSfhbZwc95Pvz0SNu8uu9SkHWGHhA1EieGpDcsCGaWjPVW0VyEHwtHWygevmEzjA7nt9kyGwk/7J+/xg3jboFozli0CvZJU3Mp7uH94SFgxc1Trrr1hbxP86DytuMn8aXM/W224N2Fs7wELEV3yJY0IXeJ2g/2KMhPmc83a4Ozx2ygDmp15noDtEJMn6VV6xviD6Xsog+BQTE2JRZG3+RuN2GCgoFgADo+UFhdEKF71LgAL8rOeGBFPjLXwMh6jykvmb9zRQm/DU5uy8DVVcy3FVVzrBrSIjhmMoxUsQvCYpw3siApDHnLBcQi49waQfBR/NrSfvtEqHDEKOK9Zx6qNlEU/ckjtCkaqmJiPu/ftalzdp3DRsu3xTypE/kjdS05bmRk+E/UnUSq0QkXTJgM7EF0aSF1J9XasAAq4ty0si8BLRjW53obi912dGZLavN328HjwKC7ngwgxYb2h9tfmaBhEEfN64w25IpiHKH0L4W4yPZAZmxvEifwPTa7H2URVpUVqAYoNLucTYOFAo/De8GwsO4hxrncg8S3Gxjk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
